name: validate cmgd metadata
on: [workflow_dispatch]
jobs:
  validate-cmgd-metadata:
    #runs-on: quanwan89/linkml-cmgd
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install csv2json
        run: npm install --global csv2json
      - name: Install linkml
        run: |
          python -m pip install --upgrade pip
          pip install linkml
      - name: convert csv to json
        run: |
          gen-json-schema $GITHUB_WORKSPACE/schema.yaml > schema.json
          csv2json -d -t $GITHUB_WORKSPACE/inst/curated/AsnicarF_2017/AsnicarF_2017_metadata.tsv test.json
          node $GITHUB_WORKSPACE/scripts/postConversion.js
          sed -i '1s/^/{"samples":/' new_test.json
          echo '}' >> new_test.json
      - name: jsonschema validate
        continue-on-error: true
        run: |
          jsonschema -i new_test.json schema.json &> results.txt
          cat results.txt
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      - name: Commit Exports
        run: |
          git add results.txt
          git commit -m "validation update"
          git push origin main
