name: validate cmgd metadata
on: [workflow_dispatch]
jobs:
  validate-cmgd-metadata:
    #runs-on: quanwan89/linkml-cmgd
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install csv2json
        run: npm install --global csv2json
      - name: Install linkml
        run: |
          python -m pip install --upgrade pip
          pip install linkml
      - name: convert csv to json && jsonschema validate
        continue-on-error: true
        run: |
          sh $GITHUB_WORKSPACE/scripts/batch.sh
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      - name: Commit Exports
        run: |
          git add results.txt
          git add new_test.json
          git commit -m "validation update"
          git push origin main
